### ISSUE TITLE
Missing DESCRIPTION file on github

### ISSUE THREAD

**Issue by caprice-j** [systemincloud/rly#3]
Is there any way to use your github repository as R package?

I tried to pull your fix into my local rly package by devtools::install_github(),
but it returned `Does not appear to be an R package (no DESCRIPTION)` error.
DESCRIPTION file is now in .gitignore and not on github.

**Comment by marekjagielski** [comment]
I didn't know about possibility of 'devtools::install_github()'. My DESCRIPTION file is generated during mvn install. I introduced mvn wrapper for automatization purpose of all my builds. I think I can commit also generated DESCRIPTION file to make it compatible with devtools::install_github().

Anyway. To install R package I do 'mvn install'.

**Comment by caprice-j** [comment]
"mvn install" worked! Thank you.
