### ISSUE TITLE
Passing Variables between Tokenizing/Parsing Rules

### ISSUE THREAD

**Issue by caprice-j** [systemincloud/rly#4]
It it possible to pass variables between t_* and p_* functions?
Currently I've just defined an environment globally and access it, but other ways might be much cleaner.

**Comment by marekjagielski** [comment]
Lexer and Parser that you defines are R6 classes that are initialized in function rly::lex and rly::yacc. You could add your own fields like:

```R
Lexer <- R6::R6Class("Lexer",
    public = list(
    tokens = TOKENS,
    literals = LITERALS,
    myvar = NA,
    initialize = function(myvar) {
      self$myvar <- myvar
    },
    t_NAME = '[a-zA-Z_][a-zA-Z0-9_]*',
    ...

lexer  <- rly::lex(Lexer, list(3))
```

and manipulate on them. From parser you could access these values by:

```R
p$lexer$instance$myvar
```

**Comment by marekjagielski** [comment]
If you think it is needed, I could also consider to have LexToken unlocked (need to analyse the consequences) or add a list container for additional data to have possibility to attach custom values.

**Comment by caprice-j** [comment]
I'll try R6 fields first in a few days.
My usage is a little different from usual lex/yacc usage, and I'm not sure more fields in tokens have values in tokenizing in general. I think R6 fields suffice.

**Comment by caprice-j** [comment]
It turned out all of my requirements met by R6 additional field. Great design.
FYI, my requirements are:

1. to pass variables from my lex caller to lex:
     rly::lex(Lexer, "myval") //     call   $initialize(myval) { self$myvar = myval }
2. to use the variables in lexer : self$myvar
3. to use the variables in parser: p$lexer$instance$myvar  (as you mentioned)
4. to use the variables after parsing: lexer$instance$myvar

Thank you for your information.
