### ISSUE TITLE
dynamic regex in function

### ISSUE THREAD

**Issue by HenricoWitvliet** [systemincloud/rly#5]
I like this library. But I think I'm using it in a wrong way. I try to build a dynamic parser. I build a regular expression using the labels I expect, and I try to use that variable as the re-argument for a lexer token:

    reLABEL <- '(label1|label2|....'
    ....
    lexer <- R6Class("Lexer",
      ....
      t_LABEL = function(re = reLABEL, t) {

In the function *get_regex* the value is not a string, but is of class "name" and has the value reLABEL. 

It seems that the following change works for me:

    get_regex = function(func) {
      val <- formals(func)[['re']]
      if (!is(val, 'character')) {
        val <- eval(val, parent.env(environment(func)))
      }
      return(val)
    }

Do you know a better way to use variables containing the string with the regular expression?

**Comment by marekjagielski** [comment]
Hi,
Thank you for your feedback. I think your proposition is valid. Please provide a pull request.
rly is a clone of python ply library. 
I see that in this origin library we have such possibility by using TOKEN decorator:
http://www.eng.utah.edu/~cs3100/lectures/l14/ply-3.4/doc/ply.html#ply_nn14
So I suppose that we should have it to also in rly.

**Comment by HenricoWitvliet** [comment]
Ok, I'll make a pull request with my change and some testcases. It will take at least a week before I have time.
If I only use `environment(func)` it also works, and you get to see the list where the lexer is defined. Adding the required variable to the list seems closer to the ply-version. But in the case of R it makes more sense to me to use a defined variable and expect R to find it in the right scope.

**Comment by marekjagielski** [comment]
It will be available in 1.6.0
